# Generated by Django 6.0.6 on 2026-06-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certname', models.CharField(max_length=150)),
                ('certorg', models.CharField(max_length=150)),
                ('cerdesc', models.CharField(blank=True, max_length=150)),
                ('issued_on', models.DateField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('cerfurl', models.URLField(blank=True)),
                ('cerlogo', models.ImageField(blank=True, upload_to='certifications/')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_type', models.CharField(choices=[('PG', 'PG'), ('UG', 'UG'), ('Intermediate', 'Intermediate'), ('SSC', 'SSC')], max_length=150)),
                ('university_name', models.CharField(blank=True, max_length=150)),
                ('institute_name', models.CharField(max_length=150)),
                ('course_degree', models.CharField(max_length=150)),
                ('branch', models.CharField(blank=True, max_length=150)),
                ('yearofpass', models.CharField(max_length=150)),
                ('modeofstudy', models.CharField(choices=[('FullTime', 'FullTime'), ('PartTime', 'PartTime'), ('Distinct', 'Distinct')], max_length=150)),
                ('score', models.PositiveIntegerField()),
                ('edu_desc', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prjct_type', models.CharField(choices=[('mini', 'Mini'), ('major', 'Major')], default='mini', max_length=150)),
                ('prjectname', models.CharField(max_length=150)),
                ('projctdsc', models.CharField(blank=True, max_length=150)),
                ('skillsinvolve', models.CharField(max_length=150)),
                ('prj_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skname', models.CharField(max_length=150)),
                ('skprofec', models.PositiveIntegerField()),
                ('sklogo', models.ImageField(blank=True, upload_to='skills/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('mobile', models.CharField(max_length=150)),
                ('gndr', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('gitlink', models.URLField(blank=True)),
                ('fblink', models.URLField(blank=True)),
                ('linkdinlink', models.URLField(blank=True)),
                ('twerlink', models.URLField(blank=True)),
                ('abotme', models.TextField(blank=True)),
            ],
        ),
    ]
